apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdg-blog-harbor-registry
  labels:
    name: bdg-blog-harbor-registry
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    # you must make directory before create pv.
    path: /mnt/bdg-blog/harbor/registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - deagwon
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdg-blog-harbor-chartmuseum
  labels:
    name: bdg-blog-harbor-chartmuseum
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    # you must make directory before create pv.
    path: /mnt/bdg-blog/harbor/chartmuseum
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - deagwon
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdg-blog-harbor-redis
  labels:
    name: bdg-blog-harbor-redis
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    # you must make directory before create pv.
    path: /mnt/bdg-blog/harbor/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - deagwon
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdg-blog-harbor-jobservice
  labels:
    name: bdg-blog-harbor-jobservice
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    # you must make directory before create pv.
    path: /mnt/bdg-blog/harbor/jobservice
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - deagwon
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdg-blog-harbor-trivy
  labels:
    name: bdg-blog-harbor-trivy
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    # you must make directory before create pv.
    path: /mnt/bdg-blog/harbor/trivy
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - deagwon
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdg-blog-harbor-database
  labels:
    name: bdg-blog-harbor-database
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    # you must make directory before create pv.
    path: /mnt/bdg-blog/harbor/database
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - deagwon