apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: bdg-blog-harbor
spec:
  secretName: crt-secret
  dnsNames:
    - harbor.deagwon.com
  issuerRef:
    name: issuer
    kind: Issuer