apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bdg-blog-harbor
metadata:
  name: bdg-blog-harbor
generatorOptions:
  disableNameSuffixHash: true
resources:
- 00namespace.yaml
- 01harbor-pv.yaml
- 02harbor-pvc.yaml
- 03issuer.yaml
- 04certificate.yaml
- 05ingress.yaml
helmCharts:
- includeCRDs: true
  name: harbor
  namespace: bdg-blog-harbor
  releaseName: harbor
  repo: https://helm.goharbor.io
  valuesFile: 06harbor-helm-values.yaml
  version: 1.11.1
