apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gocd-pv-claim
  namespace: gocd
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi