apiVersion: v1
kind: PersistentVolume
metadata:
  name: gocd-pv
  namespace: gocd
spec:
   capacity:
      storage: 2Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: local-path
   local:
      path: /mnt/gocd
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - deagwon