apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gocd
metadata:
  name: arbitrary
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
  - name: go-password
    files:
      - go-password=go-password
resources:
  - gocd-pv.yaml
  - gocd-pvc.yaml
  - ingress.yaml
