apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-webhook-sa
  namespace: bdg-blog-argoci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-webhook-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-events-webhook
subjects:
- kind: ServiceAccount
  name: argo-events-webhook-sa
  namespace: bdg-blog-argoci
---
apiVersion: v1
kind: Service
metadata:
  name: events-webhook
  namespace: bdg-blog-argoci
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: events-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-webhook
  namespace: bdg-blog-argoci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-webhook
  template:
    metadata:
      labels:
        app: events-webhook
    spec:
      containers:
      - args:
        - webhook-service
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PORT
          value: "443"
        image: quay.io/argoproj/argo-events:v1.7.6
        imagePullPolicy: Always
        name: webhook
      serviceAccountName: argo-events-webhook-sa
