apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argo-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: azaz09112@naver.com
    privateKeySecretRef:
      name: argo-issuer
    solvers:
    - http01:
        ingress:
           class: traefik-cert-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-certificate
spec:
  secretName: argo-crt-secret
  dnsNames:
    - ci2.argo.deagwon.com
    - webhook2.argo.deagwon.com
  issuerRef:
    name: argo-issuer
    kind: Issuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-argo-redirect
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ci2.argo.deagwon.com`)
      kind: Rule
      services:
        - name: argo-server
          port: 2746
      middlewares:
        - name: redirectscheme
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-argo
  annotations:
    cert-manager.io/issuer: argo-issuer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ci2.argo.deagwon.com`)
      kind: Rule
      services:
        - name: argo-server
          port: 2746
    - match: Host(`webhook2.argo.deagwon.com`)
      kind: Rule
      services:
        - name: github-eventsource-svc
          port: 12000
  tls:
    secretName: argo-crt-secret