apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-ci
generatorOptions:
  disableNameSuffixHash: true
resources:
  # argo workflows
  - namespace.yaml
  - https://github.com/argoproj/argo-workflows/releases/download/v3.4.5/install.yaml
  - role.yaml
  # workflow
  # - kaniko/workflow.yaml
  # argo events
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml
  - https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install-validating-webhook.yaml
  - event-bus.yaml
  - event-source.yaml
  - event-rbac.yaml
  # ingress
  - ingress.yaml
patchesStrategicMerge:
  - argo-patch.yaml
secretGenerator:
  - name: git-secret
    envs:
    - kaniko/git-secret
configMapGenerator:
- name: harbor-config
  files:
    - kaniko/config.json