apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bdg-blog-argoci
generatorOptions:
  disableNameSuffixHash: true
resources:
  # argo workflows
  - 00namespace.yaml
  - 01argo-workflows.yaml
  - 02workflow-rbac.yaml
  - 03rollout-rbac.yaml
  # argo events
  - 11argo-events-install.yaml
  - 12argo-event-webhook-install.yaml
  - 13event-bus.yaml
  - 14event-source.yaml
  - 15event-rbac.yaml
  - 16event-sensor.yaml
  # ingress
  - 21ingress.yaml
patchesStrategicMerge:
  - 31argo-patch.yaml
secretGenerator:
  - name: git-secret
    envs:
      - kaniko/git-secret
  - name: git-ssh
    files:
      - .ssh/id_rsa
  - name: git-known-hosts
    files:
      - .ssh/known_hosts
configMapGenerator:
  - name: harbor-config
    files:
      - kaniko/config.json
  - name: rollout-kubeconfig
    files:
      - rollout/config
