apiVersion: v1
kind: Pod
metadata:
  name: bdg-blog-v2-builder
  namespace: bdg-blog-v2-builder
spec:
  containers:
  - name: bdg-blog-v2-builder
    image: gcr.io/kaniko-project/executor:latest
    imagePullPolicy: Always
    args:
    - "--dockerfile=Dockerfile"
    - "--context=git://github.com/deagwon97/bdg-blog-v2.git"
    - "--destination=harbor.deagwon.com/bdg-blog/bdg-blog-v2:latest"
    - "--cache=true"
    envFrom:
    - secretRef:
        name: git-secret
    volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
  volumes:
    - name: docker-config
      configMap:
        name: harbor-config
  restartPolicy: Never
  nodeName: bdg-msi
  