apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bdg-blog-v2-builder
metadata:
  name: arbitrary
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
  - name: git-secret
    envs:
    - git-secret
configMapGenerator:
- name: harbor-config
  files:
    - config.json
commonLabels:
  app: bdg-blog-v2
resources:
  - kaniko.yaml
  