apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdg-blog-mariadb-pv
  labels:
    name: bdg-blog-mariadb-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    # you must make directory before create pv.
    path: /mnt/bdg-blog/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - bdg-msi