apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: bdg-blog-mariadb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: mariadb
      port: 3313
      targetPort: 3306
  selector:
    app: mariadb
