version: "3.9"

services:
  bdg-blog:
    container_name: bdg-blog
    build:
      context: ../
      dockerfile: ./Dockerfile # context 경로 기준 상대경로
      target: builder
    volumes: # docker-comose 파일 경로 기준 상대 경로
      - ../:/workdir
    ports:
      - 3991:3000
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: /bin/sh
    privileged: true
