kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: bdg-blog
spec:
  project: default
  source:
    repoURL: 'https://github.com/deagwon97/bdg-blog-v2'
    path: deploy/kustomize/production
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bdg-blog
  syncPolicy:
    automated: {}

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: bdg-blog-argoci
spec:
  project: default
  source:
    repoURL: 'https://github.com/deagwon97/bdg-blog-v2'
    path: deploy/argoci
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argoci-bdg-blog
  syncPolicy:
    automated: {}

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: bdg-blog-argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/deagwon97/bdg-blog-v2'
    path: deploy/argocd
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bdg-blog-argocd
  syncPolicy:
    automated: {}

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: bdg-blog-harbor
spec:
  project: default
  source:
    repoURL: 'https://github.com/deagwon97/bdg-blog-v2'
    path: deploy/harbor
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bdg-blog-harbor
  syncPolicy:
    automated: {}

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: bdg-blog-minio
spec:
  project: default
  source:
    repoURL: 'https://github.com/deagwon97/bdg-blog-v2'
    path: deploy/minio
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bdg-blog-minio
  syncPolicy:
    automated: {}
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: bdg-blog-mariadb
spec:
  project: default
  source:
    repoURL: 'https://github.com/deagwon97/bdg-blog-v2'
    path: deploy/mariadb
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bdg-blog-mariadb
  syncPolicy:
    automated: {}

---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: bdg-blog-redis
spec:
  project: default
  source:
    repoURL: 'https://github.com/deagwon97/bdg-blog-v2'
    path: deploy/redis
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bdg-blog-redis
  syncPolicy:
    automated: