apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  namespace: bdg-blog-argocd
  name: argocd-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: azaz09112@naver.com
    privateKeySecretRef:
      name: argocd-issuer
    solvers:
    - http01:
        ingress:
           class: traefik-cert-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: bdg-blog-argocd
  name: argocd-certificate
spec:
  secretName: argocd-crt-secret
  dnsNames:
    - cd.argo.deagwon.com
  issuerRef:
    name: argocd-issuer
    kind: Issuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: bdg-blog-argocd
  name: redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: bdg-blog-argocd
  name: ingressroute-argocd-redirect
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`cd.argo.deagwon.com`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: redirectscheme
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-argocd
  namespace: bdg-blog-argocd
  annotations:
    cert-manager.io/issuer: argocd-issuer
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`cd.argo.deagwon.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`cd.argo.deagwon.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-crt-secret
