apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bdg-blog-argocd
resources:
  - namespace.yaml
  - custom-install.yaml
  - ingress.yaml
  # - repository.yaml # hide repository resource for argocd application sync.
  - application.yaml
patches:
  - argocd-cmd-params-cm-patch.yml
