apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bdg-blog
  name: bdg-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bdg-blog
  template:
    metadata:
      labels:
        app: bdg-blog
    spec:
      containers:
      - name: bdg-blog
        image: harbor.deagwon.com/bdg-blog/bdg-blog:latest
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 3000
        envFrom:
            - secretRef:
                name: bdg-blog
      serviceAccountName: bdg-blog-regcred 
      imagePullSecrets:
        - name: bdg-blog-regcred 
