apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bdg-blog-certificate
  namespace: bdg-blog
spec:
  secretName: bdg-blog-crt-secret
  dnsNames:
    - deagwon.com
  issuerRef:
    name: bdg-blog-issuer
    kind: Issuer