apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bdg-blog-v2-certificate
  namespace: bdg-blog-v2
spec:
  secretName: bdg-blog-v2-crt-secret
  dnsNames:
    - v2.deagwon.com
  issuerRef:
    name: bdg-blog-v2-issuer
    kind: Issuer