apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-bdg-blog-redirect
  namespace: bdg-blog
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`deagwon.com`)
      kind: Rule
      services:
        - name: bdg-blog
          port: 3000
      middlewares:
        - name: redirectscheme
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-bdg-blog
  namespace: bdg-blog
  annotations:
    cert-manager.io/issuer: bdg-blog-issuer
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`deagwon.com`)
      kind: Rule
      services:
        - name: bdg-blog
          port: 3000
  tls:
    secretName: bdg-blog-crt-secret