apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bdg-blog
metadata:
  name: arbitrary
generatorOptions:
  disableNameSuffixHash: true
## generate secret only first time
# secretGenerator:
#   - name: bdg-blog
#     envs:
#     - 01nextjs.env
#   - name: bdg-blog-regcred
#     files:
#       - .dockerconfigjson=01dockerconfig.json
#     type: kubernetes.io/dockerconfigjson
commonLabels:
  app: bdg-blog
resources:
  - 00namespace.yaml
  - 03serviceAccount.yaml
  - 04deployment.yaml
  - 05service.yaml
  - 11issuer.yaml
  - 12certificate.yaml
  - 13middleWare.yaml
  - 14ingressRouter.yaml
