nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

yarnPath: .yarn/releases/yarn-3.3.0.cjs
# prisma@*:
#   dependencies:
#     "resolve": "*"
# '@prisma/client@*':
#   dependencies:
#     '.prisma': 'link:See "resolution" field of package.json'
